"""
Django settings for brightly_blog project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v5e!l!ym!0oqh%=8y28of&f9(ilk(cnt668r2*z)q0lt&kh10f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sitemaps',
    'django_ckeditor_5',
    'hitcount',
    'blog',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # ADD THIS 2nd
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "brightly_blog.urls"

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]

WSGI_APPLICATION = "brightly_blog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # This is what was missing
STATICFILES_DIRS = [BASE_DIR / 'static']
CKEDITOR_5_UPLOAD_PATH = "uploads/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(37, 98%, 53%)", "label": "Orange"},
    {"color": "hsl(208, 100%, 50%)", "label": "Blue"},
]


CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',

            # Text formatting
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'subscript',
            'superscript',
            '|',

            # Fonts
            'fontSize',
            'fontFamily',
            'fontColor',
            'fontBackgroundColor',
            '|',

            # Paragraph formatting
            'alignment',
            'outdent',
            'indent',
            '|',

            # Lists
            'bulletedList',
            'numberedList',
            'todoList',
            '|',

            # Insert
            'link',
            'imageUpload',
            'insertTable',
            'blockQuote',
            'mediaEmbed',
            'horizontalLine',
            'specialCharacters',
            '|',

            # Code
            'code',
            'codeBlock',
            '|',

            # Undo
            'undo',
            'redo'
        ],

        'heading': {
            'options': [
                {
                    'model': 'paragraph',
                    'title': 'Paragraph',
                    'class': 'ck-heading_paragraph'
                },
                {
                    'model': 'heading1',
                    'view': 'h1',
                    'title': 'Heading 1',
                    'class': 'ck-heading_heading1'
                },
                {
                    'model': 'heading2',
                    'view': 'h2',
                    'title': 'Heading 2',
                    'class': 'ck-heading_heading2'
                },
                {
                    'model': 'heading3',
                    'view': 'h3',
                    'title': 'Heading 3',
                    'class': 'ck-heading_heading3'
                },
                {
                    'model': 'heading4',
                    'view': 'h4',
                    'title': 'Heading 4',
                    'class': 'ck-heading_heading4'
                },
                {
                    'model': 'heading5',
                    'view': 'h5',
                    'title': 'Heading 5',
                    'class': 'ck-heading_heading5'
                },
                {
                    'model': 'heading6',
                    'view': 'h6',
                    'title': 'Heading 6',
                    'class': 'ck-heading_heading6'
                },
            ]
        },

        # Font sizes
        'fontSize': {
            'options': [
                9,
                11,
                13,
                'default',
                17,
                19,
                21,
                24,
                28,
                32,
                36
            ]
        },

        # Font families
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Tahoma, sans-serif',
                'Times New Roman, Times, serif',
                'Verdana, sans-serif'
            ]
        },

        # Images
        'image': {
            'toolbar': [
                'imageTextAlternative',
                '|',
                'imageStyle:inline',
                'imageStyle:alignLeft',
                'imageStyle:alignCenter',
                'imageStyle:alignRight',
                'imageStyle:block',
                '|',
                'resizeImage'
            ]
        },

        # Tables
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ]
        },

        # Media embeds
        'mediaEmbed': {
            'previewsInData': True
        },

        # Code blocks
        'codeBlock': {
            'languages': [
                {'language': 'plaintext', 'label': 'Plain text'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'sql', 'label': 'SQL'},
            ]
        },
    }
}

# FIX FOR TERMUX FILE LOCK ERROR
import sys
if 'termux' in sys.executable or '/data/data/com.termux' in sys.executable:
    from django.core.files import locks
    def dummy_lock(f, flags):
        pass
    def dummy_unlock(f):
        pass
    locks.lock = dummy_lock
    locks.unlock = dummy_unlock
    

# settings.py
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5MB
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

HITCOUNT_KEEP_HIT_ACTIVE = {'days': 1} # count 1 view per user per day
HITCOUNT_HITS_PER_IP_LIMIT = 0 # 0 = no limit
HITCOUNT_EXCLUDE_USER_GROUP = [] # who to exclude from counting

LOGIN_REDIRECT_URL = 'home' 
LOGOUT_REDIRECT_URL = 'home'